// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk/models/shared"
	"net/http"
)

type CreatePersonalLabelRequest struct {
	// Name of the label.
	Name string `queryParam:"style=form,explode=true,name=name"`
	// Label order.
	Order *int64 `queryParam:"style=form,explode=true,name=order"`
	// The color of the label icon. Refer to the name column in the Colors guide for more info.
	Color *string `queryParam:"style=form,explode=true,name=color"`
	// Whether the label is a favorite (a true or false value).
	IsFavorite *bool `queryParam:"style=form,explode=true,name=is_favorite"`
}

func (o *CreatePersonalLabelRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreatePersonalLabelRequest) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *CreatePersonalLabelRequest) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *CreatePersonalLabelRequest) GetIsFavorite() *bool {
	if o == nil {
		return nil
	}
	return o.IsFavorite
}

type CreatePersonalLabelResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Label created.
	Label *shared.Label
	// Unexpected error
	ErrorModel *shared.ErrorModel
}

func (o *CreatePersonalLabelResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreatePersonalLabelResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreatePersonalLabelResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreatePersonalLabelResponse) GetLabel() *shared.Label {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *CreatePersonalLabelResponse) GetErrorModel() *shared.ErrorModel {
	if o == nil {
		return nil
	}
	return o.ErrorModel
}
