// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk/models/shared"
	"net/http"
)

type GetActiveTaskRequest struct {
	// The ID of the task to retrieve.
	TaskID int64 `pathParam:"style=simple,explode=false,name=taskId"`
}

func (o *GetActiveTaskRequest) GetTaskID() int64 {
	if o == nil {
		return 0
	}
	return o.TaskID
}

type GetActiveTaskResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Task details.
	Task *shared.Task
	// Unexpected error
	ErrorModel *shared.ErrorModel
}

func (o *GetActiveTaskResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetActiveTaskResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetActiveTaskResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetActiveTaskResponse) GetTask() *shared.Task {
	if o == nil {
		return nil
	}
	return o.Task
}

func (o *GetActiveTaskResponse) GetErrorModel() *shared.ErrorModel {
	if o == nil {
		return nil
	}
	return o.ErrorModel
}
