// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk/models/shared"
	"net/http"
)

type GetActiveTasksRequest struct {
	// Filter tasks by project ID.
	ProjectID *string `queryParam:"style=form,explode=true,name=project_id"`
	// Filter tasks by section ID.
	SectionID *string `queryParam:"style=form,explode=true,name=section_id"`
	// Filter tasks by label name.
	Label *string `queryParam:"style=form,explode=true,name=label"`
	// Filter by any supported filter.
	Filter *string `queryParam:"style=form,explode=true,name=filter"`
	// IETF language tag defining what language the filter is written in, if it differs from the default English.
	Lang *string `queryParam:"style=form,explode=true,name=lang"`
	// A list of the task IDs to retrieve, this should be a comma-separated list.
	Ids []int64 `queryParam:"style=form,explode=true,name=ids"`
}

func (o *GetActiveTasksRequest) GetProjectID() *string {
	if o == nil {
		return nil
	}
	return o.ProjectID
}

func (o *GetActiveTasksRequest) GetSectionID() *string {
	if o == nil {
		return nil
	}
	return o.SectionID
}

func (o *GetActiveTasksRequest) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *GetActiveTasksRequest) GetFilter() *string {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *GetActiveTasksRequest) GetLang() *string {
	if o == nil {
		return nil
	}
	return o.Lang
}

func (o *GetActiveTasksRequest) GetIds() []int64 {
	if o == nil {
		return nil
	}
	return o.Ids
}

type GetActiveTasksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of active tasks.
	Tasks []shared.Task
	// Unexpected error
	ErrorModel *shared.ErrorModel
}

func (o *GetActiveTasksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetActiveTasksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetActiveTasksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetActiveTasksResponse) GetTasks() []shared.Task {
	if o == nil {
		return nil
	}
	return o.Tasks
}

func (o *GetActiveTasksResponse) GetErrorModel() *shared.ErrorModel {
	if o == nil {
		return nil
	}
	return o.ErrorModel
}
