// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk/models/shared"
	"net/http"
)

type GetAllSectionsRequest struct {
	// Project ID.
	ProjectID *string `queryParam:"style=form,explode=true,name=project_id"`
}

func (o *GetAllSectionsRequest) GetProjectID() *string {
	if o == nil {
		return nil
	}
	return o.ProjectID
}

type GetAllSectionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// An array of all sections.
	Sections []shared.Section
	// Unexpected error
	ErrorModel *shared.ErrorModel
}

func (o *GetAllSectionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllSectionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllSectionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllSectionsResponse) GetSections() []shared.Section {
	if o == nil {
		return nil
	}
	return o.Sections
}

func (o *GetAllSectionsResponse) GetErrorModel() *shared.ErrorModel {
	if o == nil {
		return nil
	}
	return o.ErrorModel
}
