// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk/models/shared"
	"net/http"
)

type GetCommentRequest struct {
	// The ID of the comment to retrieve.
	CommentID int64 `pathParam:"style=simple,explode=false,name=comment_id"`
}

func (o *GetCommentRequest) GetCommentID() int64 {
	if o == nil {
		return 0
	}
	return o.CommentID
}

type GetCommentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Comment details.
	Comment *shared.Comment
	// Unexpected error
	ErrorModel *shared.ErrorModel
}

func (o *GetCommentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCommentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCommentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetCommentResponse) GetComment() *shared.Comment {
	if o == nil {
		return nil
	}
	return o.Comment
}

func (o *GetCommentResponse) GetErrorModel() *shared.ErrorModel {
	if o == nil {
		return nil
	}
	return o.ErrorModel
}
