// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk/models/shared"
	"net/http"
)

type GetSingleSectionRequest struct {
	// Section ID.
	SectionID string `pathParam:"style=simple,explode=false,name=sectionId"`
}

func (o *GetSingleSectionRequest) GetSectionID() string {
	if o == nil {
		return ""
	}
	return o.SectionID
}

type GetSingleSectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Section retrieved.
	Section *shared.Section
	// Unexpected error
	ErrorModel *shared.ErrorModel
}

func (o *GetSingleSectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSingleSectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSingleSectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSingleSectionResponse) GetSection() *shared.Section {
	if o == nil {
		return nil
	}
	return o.Section
}

func (o *GetSingleSectionResponse) GetErrorModel() *shared.ErrorModel {
	if o == nil {
		return nil
	}
	return o.ErrorModel
}
