// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk/models/shared"
	"net/http"
)

type UpdatePersonalLabelRequest struct {
	// The ID of the label to update.
	LabelID string `pathParam:"style=simple,explode=false,name=label_id"`
	// New name of the label.
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// Number that is used by clients to sort the list of labels.
	Order *int64 `queryParam:"style=form,explode=true,name=order"`
	// The color of the label icon. Refer to the name column in the Colors guide for more info.
	Color *string `queryParam:"style=form,explode=true,name=color"`
	// Whether the label is a favorite (a true or false value).
	IsFavorite *bool `queryParam:"style=form,explode=true,name=is_favorite"`
}

func (o *UpdatePersonalLabelRequest) GetLabelID() string {
	if o == nil {
		return ""
	}
	return o.LabelID
}

func (o *UpdatePersonalLabelRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdatePersonalLabelRequest) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *UpdatePersonalLabelRequest) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *UpdatePersonalLabelRequest) GetIsFavorite() *bool {
	if o == nil {
		return nil
	}
	return o.IsFavorite
}

type UpdatePersonalLabelResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Label updated.
	Label *shared.Label
	// Unexpected error
	ErrorModel *shared.ErrorModel
}

func (o *UpdatePersonalLabelResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdatePersonalLabelResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdatePersonalLabelResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdatePersonalLabelResponse) GetLabel() *shared.Label {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *UpdatePersonalLabelResponse) GetErrorModel() *shared.ErrorModel {
	if o == nil {
		return nil
	}
	return o.ErrorModel
}
