// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk/models/shared"
	"net/http"
)

type UpdateCommentRequest struct {
	// The ID of the comment to update.
	CommentID string `pathParam:"style=simple,explode=false,name=comment_id"`
	// New content for the comment. This value may contain markdown-formatted text and hyperlinks.
	Content string `queryParam:"style=form,explode=true,name=content"`
}

func (o *UpdateCommentRequest) GetCommentID() string {
	if o == nil {
		return ""
	}
	return o.CommentID
}

func (o *UpdateCommentRequest) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

type UpdateCommentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Comment updated.
	Comment *shared.Comment
	// Unexpected error
	ErrorModel *shared.ErrorModel
}

func (o *UpdateCommentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateCommentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateCommentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateCommentResponse) GetComment() *shared.Comment {
	if o == nil {
		return nil
	}
	return o.Comment
}

func (o *UpdateCommentResponse) GetErrorModel() *shared.ErrorModel {
	if o == nil {
		return nil
	}
	return o.ErrorModel
}
