// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Duration struct {
	// A positive (greater than zero) integer for the amount of duration_unit the task will take, or null to unset. If specified, you must define a duration_unit.
	Amount *int64 `json:"amount,omitempty"`
	// The unit of time that the duration field above represents, or null to unset. Must be either minute or day. If specified, duration must be defined as well.
	Unit *string `json:"unit,omitempty"`
}

func (o *Duration) GetAmount() *int64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *Duration) GetUnit() *string {
	if o == nil {
		return nil
	}
	return o.Unit
}
