// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Label struct {
	// Label ID.
	ID *string `json:"id,omitempty"`
	// Label name.
	Name *string `json:"name,omitempty"`
	// The color of the label icon. Refer to the name column in the Colors guide for more info.
	Color *string `json:"color,omitempty"`
	// Number used by clients to sort list of labels.
	Order *int64 `json:"order,omitempty"`
	// Whether the label is a favorite (a true or false value).
	IsFavorite *bool `json:"is_favorite,omitempty"`
}

func (o *Label) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Label) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Label) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *Label) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *Label) GetIsFavorite() *bool {
	if o == nil {
		return nil
	}
	return o.IsFavorite
}
