// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Project struct {
	// Project ID.
	ID *string `json:"id,omitempty"`
	// Project name.
	Name *string `json:"name,omitempty"`
	// The color of the project icon. Refer to the name column in the Colors guide for more info.
	Color *string `json:"color,omitempty"`
	// ID of parent project (will be null for top-level projects).
	ParentID *string `json:"parent_id,omitempty"`
	// Project position under the same parent (read-only, will be 0 for inbox and team inbox projects).
	Order *int64 `json:"order,omitempty"`
	// Number of project comments.
	CommentCount *int64 `json:"comment_count,omitempty"`
	// Whether the project is shared (read-only, a true or false value).
	IsShared *bool `json:"is_shared,omitempty"`
	// Whether the project is a favorite (a true or false value).
	IsFavorite *bool `json:"is_favorite,omitempty"`
	// Whether the project is the user's Inbox (read-only).
	IsInboxProject *bool `json:"is_inbox_project,omitempty"`
	// Whether the project is the Team Inbox (read-only).
	IsTeamInbox *bool `json:"is_team_inbox,omitempty"`
	// A string value (either list or board). This determines the way the project is displayed within the Todoist clients.
	ViewStyle *string `json:"view_style,omitempty"`
	// URL to access this project in the Todoist web or mobile applications.
	URL *string `json:"url,omitempty"`
}

func (o *Project) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Project) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Project) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *Project) GetParentID() *string {
	if o == nil {
		return nil
	}
	return o.ParentID
}

func (o *Project) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *Project) GetCommentCount() *int64 {
	if o == nil {
		return nil
	}
	return o.CommentCount
}

func (o *Project) GetIsShared() *bool {
	if o == nil {
		return nil
	}
	return o.IsShared
}

func (o *Project) GetIsFavorite() *bool {
	if o == nil {
		return nil
	}
	return o.IsFavorite
}

func (o *Project) GetIsInboxProject() *bool {
	if o == nil {
		return nil
	}
	return o.IsInboxProject
}

func (o *Project) GetIsTeamInbox() *bool {
	if o == nil {
		return nil
	}
	return o.IsTeamInbox
}

func (o *Project) GetViewStyle() *string {
	if o == nil {
		return nil
	}
	return o.ViewStyle
}

func (o *Project) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
