// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Section struct {
	// Section ID
	ID *string `json:"id,omitempty"`
	// ID of the project section belongs to
	ProjectID *string `json:"project_id,omitempty"`
	// Section position among other sections from the same project
	Order *int64 `json:"order,omitempty"`
	// Section name
	Name *string `json:"name,omitempty"`
}

func (o *Section) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Section) GetProjectID() *string {
	if o == nil {
		return nil
	}
	return o.ProjectID
}

func (o *Section) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *Section) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
