// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	tfTypes "github.com/speakeasy/terraform-provider-todoist/internal/provider/types"
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk"
	"github.com/speakeasy/terraform-provider-todoist/internal/sdk/models/operations"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &TaskDataSource{}
var _ datasource.DataSourceWithConfigure = &TaskDataSource{}

func NewTaskDataSource() datasource.DataSource {
	return &TaskDataSource{}
}

// TaskDataSource is the data source implementation.
type TaskDataSource struct {
	client *sdk.SDK
}

// TaskDataSourceModel describes the data model.
type TaskDataSourceModel struct {
	AssigneeID   types.String          `tfsdk:"assignee_id"`
	AssignerID   types.String          `tfsdk:"assigner_id"`
	CommentCount types.Int64           `tfsdk:"comment_count"`
	Content      types.String          `tfsdk:"content"`
	CreatedAt    types.String          `tfsdk:"created_at"`
	CreatorID    types.String          `tfsdk:"creator_id"`
	Description  types.String          `tfsdk:"description"`
	Due          *tfTypes.TaskDue      `tfsdk:"due"`
	Duration     *tfTypes.TaskDuration `tfsdk:"duration"`
	ID           types.String          `tfsdk:"id"`
	IsCompleted  types.Bool            `tfsdk:"is_completed"`
	Labels       []types.String        `tfsdk:"labels"`
	Order        types.Int64           `tfsdk:"order"`
	ParentID     types.String          `tfsdk:"parent_id"`
	Priority     types.Int64           `tfsdk:"priority"`
	ProjectID    types.String          `tfsdk:"project_id"`
	SectionID    types.String          `tfsdk:"section_id"`
	URL          types.String          `tfsdk:"url"`
}

// Metadata returns the data source type name.
func (r *TaskDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_task"
}

// Schema defines the schema for the data source.
func (r *TaskDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Task DataSource",

		Attributes: map[string]schema.Attribute{
			"assignee_id": schema.StringAttribute{
				Computed:    true,
				Description: `The responsible user ID (will be null if the task is unassigned).`,
			},
			"assigner_id": schema.StringAttribute{
				Computed:    true,
				Description: `The ID of the user who assigned the task (read-only, will be null if the task is unassigned).`,
			},
			"comment_count": schema.Int64Attribute{
				Computed:    true,
				Description: `Number of task comments (read-only).`,
			},
			"content": schema.StringAttribute{
				Computed:    true,
				Description: `Task content. This value may contain markdown-formatted text and hyperlinks. Details on markdown support can be found in the Text Formatting article in the Help Center.`,
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `The date when the task was created (read-only).`,
			},
			"creator_id": schema.StringAttribute{
				Computed:    true,
				Description: `The ID of the user who created the task (read-only).`,
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: `A description for the task. This value may contain markdown-formatted text and hyperlinks. Details on markdown support can be found in the Text Formatting article in the Help Center.`,
			},
			"due": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"due_object": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"date": schema.StringAttribute{
								Computed:    true,
								Description: `Date in format YYYY-MM-DD corrected to user's timezone.`,
							},
							"datetime": schema.StringAttribute{
								Computed:    true,
								Description: `Only returned if exact due time set (i.e. it's not a whole-day task), date and time in RFC3339 format in UTC.`,
							},
							"is_recurring": schema.BoolAttribute{
								Computed:    true,
								Description: `Whether the task has a recurring due date.`,
							},
							"string": schema.StringAttribute{
								Computed:    true,
								Description: `Human defined date in arbitrary format.`,
							},
							"timezone": schema.StringAttribute{
								Computed:    true,
								Description: `Only returned if exact due time set, user's timezone definition either in tzdata-compatible format ("Europe/Berlin") or as a string specifying east of UTC offset as "UTC±HH:MM" (i.e. "UTC-01:00").`,
							},
						},
					},
				},
				Description: `Object representing task due date/time, or null if no date is set.`,
			},
			"duration": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"duration_object": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"amount": schema.Int64Attribute{
								Computed:    true,
								Description: `A positive (greater than zero) integer for the amount of duration_unit the task will take, or null to unset. If specified, you must define a duration_unit.`,
							},
							"unit": schema.StringAttribute{
								Computed:    true,
								Description: `The unit of time that the duration field above represents, or null to unset. Must be either minute or day. If specified, duration must be defined as well.`,
							},
						},
					},
				},
				Description: `Object representing a task's duration, including a positive integer for the amount of time and the unit of time (minute or day). The object will be null if the task has no duration.`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `The ID of the task to retrieve.`,
			},
			"is_completed": schema.BoolAttribute{
				Computed:    true,
				Description: `Flag to mark completed tasks.`,
			},
			"labels": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},
			"order": schema.Int64Attribute{
				Computed:    true,
				Description: `Position under the same parent or project for top-level tasks (read-only).`,
			},
			"parent_id": schema.StringAttribute{
				Computed:    true,
				Description: `ID of parent task (read-only, will be null for top-level tasks).`,
			},
			"priority": schema.Int64Attribute{
				Computed:    true,
				Description: `Task priority from 1 (normal, default value) to 4 (urgent).`,
			},
			"project_id": schema.StringAttribute{
				Computed:    true,
				Description: `Task's project ID (read-only).`,
			},
			"section_id": schema.StringAttribute{
				Computed:    true,
				Description: `ID of section task belongs to (read-only, will be null when the task has no parent section).`,
			},
			"url": schema.StringAttribute{
				Computed:    true,
				Description: `URL to access this task in the Todoist web or mobile applications (read-only).`,
			},
		},
	}
}

func (r *TaskDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *TaskDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *TaskDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	taskID := data.ID.ValueString()
	request := operations.GetActiveTaskRequest{
		TaskID: taskID,
	}
	res, err := r.client.Tasks.GetActiveTask(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.Task == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedTask(res.Task)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
