// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Due struct {
	Date        types.String `tfsdk:"date"`
	Datetime    types.String `tfsdk:"datetime"`
	IsRecurring types.Bool   `tfsdk:"is_recurring"`
	String      types.String `tfsdk:"string"`
	Timezone    types.String `tfsdk:"timezone"`
}
